name: Build

on:
  push:

jobs:
  build-backend:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
    - run: yarn install --frozen-lockfile
    - run: yarn build

  build-frontend:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'
    - run: go test -v ./...
    - run: go vet ./...
